# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=253)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('institution', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('section', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('home', models.CharField(max_length=253)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.School')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Student'),
        ),
    ]
