# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='institution',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('U', 'Univercity')], max_length=10),
        ),
    ]
