# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20191024_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
